(ns clojurecraft.model
  "The information model, in writing: every attribute the bot knows, with a one-line meaning and
   when it exists. docs/hickey.md starts here (\"Write the attribute list with namespaced names
   and one-line meanings. Everything after this is a function over that model.\"). It is data, so
   model_test can hold it in step with the code: every key a running bot writes is listed, and
   every world attribute listed has a spec. An attribute never changes meaning; a new meaning is
   a new name beside it.")

(def attributes
  "[attribute meaning when] rows, grouped by what the fact is about."
  [;; ---- the bot itself and its connection
   [:bot/phase "protocol phase: :handshake, :login, :configuration or :play; moves only in game/emit" "always"]
   [:bot/name "player name" "always"]
   [:bot/uuid "offline UUID derived from the name" "always"]
   [:bot/effects "effects the last event asked for; the loop performs and clears them" "always"]
   [:bot/sequence "last block-interaction sequence number sent" "always"]
   [:bot/closed "why the socket closed" "after it closed"]
   [:bot/disconnected "the server's disconnect reason" "after a disconnect"]
   [:conn/host "server host" "always"]
   [:conn/port "server port" "always"]
   ;; ---- time, which enters only on ticks
   [:time/now "ms of the last tick event" "always"]
   [:time/tick "ticks seen so far" "always"]
   ;; ---- facts about itself
   [:player/pos "feet-centre position [x y z]" "from the first teleport"]
   [:player/vel "velocity per tick [vx vy vz]; vy is about -0.078 at rest" "always"]
   [:player/look "[yaw pitch] in degrees" "always"]
   [:player/on-ground? "last vertical move hit ground while falling" "always"]
   [:player/horizontal-collision? "last horizontal move was blocked" "always"]
   [:player/jump-ticks "ticks until a jump is allowed again" "always"]
   [:player/loaded? "player_loaded was sent: the server lets the bot act" "always"]
   [:player/controls "what the planner wants physics to do next tick (:control/*)" "always"]
   [:player/inventory "{player-slot {:item id :count n}}: the server's word, slots 0-40" "always"]
   [:player/held-slot "selected hotbar slot 0-8" "always"]
   [:player/entity-id "the bot's entity id" "from the play login packet"]
   [:player/teleport-id "id of the last teleport accepted" "from the first teleport"]
   [:player/synced-at "ms of the last teleport" "from the first teleport"]
   [:player/health "health from set_health" "after the first set_health"]
   [:control/forward? "walk forward" "inside :player/controls"]
   [:control/jump? "jump when allowed" "inside :player/controls"]
   [:control/yaw "heading to walk on" "inside :player/controls"]
   [:control/look "[yaw pitch] to face" "inside :player/controls"]
   ;; ---- the player's screen
   [:window/grid "the 2x2 crafting grid of window 0: {cell item}, never inventory" "always"]
   [:window/cursor "the item on the cursor" "while something is carried"]
   [:window/state-id "window 0's last server state id" "after the first window 0 content"]
   [:window/open "the open container {:window/id :window/menu-type ...}" "while one is open"]
   [:window/id "container window id" "inside :window/open"]
   [:window/menu-type "container menu type id (12 is a crafting table)" "inside :window/open"]
   [:window/slots "the open container's slots" "inside :window/open"]
   ;; ---- the world as last seen, and as remembered
   [:world/chunks "{[cx cz] column}: chunks the server has sent and not forgotten" "always"]
   [:world/blocks "{[x y z] state}: block updates and own breaks over the chunks" "always"]
   [:world/entities "{entity-id {:entity/type :entity/pos :entity/seen-at}}: tracked items" "always"]
   [:world/facts "memory: DataScript value of append-only observations, never retracted" "always"]
   [:entity/type "entity type id (71 is an item)" "inside :world/entities"]
   [:entity/pos "last known entity position" "inside :world/entities"]
   [:entity/seen-at "ms the entity was added" "inside :world/entities"]
   [:sight/pos "an observation's block position" "a fact in :world/facts"]
   [:sight/state "the state id observed there" "a fact in :world/facts"]
   [:sight/at "ms of the observation" "a fact in :world/facts"]
   [:intention/id "which intent a fact is about (its :intent/id)" "a fact in :world/facts"]
   [:intention/event "what happened to it: :started :done :failed or :abandoned" "a fact in :world/facts"]
   [:intention/kind "the intent's kind" "a fact in :world/facts"]
   [:intention/at "ms it happened" "a fact in :world/facts"]
   [:intention/target "the intent's target" "a fact, when the intent had one"]
   [:intention/recipe "the intent's recipe" "a fact, when the intent had one"]
   [:intention/reason "why it failed or was abandoned (:goal-met, :preempted)" "a :failed or :abandoned fact"]
   [:answer/kind "which server answer to the bot's own action: :ack or :pickup" "a fact in :world/facts"]
   [:answer/at "ms the answer arrived" "a fact in :world/facts"]
   [:answer/sequence "the block-interaction sequence the server acknowledged" "an :ack fact"]
   [:answer/entity "the item entity the bot picked up" "a :pickup fact"]
   [:answer/count "how many items that pickup gave" "a :pickup fact"]
   ;; ---- the server's answers to the bot's own actions, and counts
   [:stats/keep-alives "keep-alives answered" "always"]
   [:stats/teleports "teleports accepted" "always"]
   [:stats/chunks "chunk columns loaded" "always"]
   [:stats/unknown "{[phase id] n}: packets with no handler" "always"]
   [:stats/last-ack "last block-changed-ack sequence from the server" "after the first ack"]
   [:stats/pickups "take-item-entity packets seen" "after the first pickup"]
   [:stats/deaths "times health fell to zero from above it" "after the first death"]
   [:net/sent-pos "position in the last movement packet" "after the first movement packet"]
   [:net/sent-look "look in the last movement packet" "after the first movement packet"]
   [:net/sent-tick "tick of the last movement packet" "after the first movement packet"]
   ;; ---- its own intentions
   [:plan/status ":landing, :active, :done or :failed" "from the :go event"]
   [:plan/goals "the target goal ids in play" "from the :go event"]
   [:plan/go-at "the landing a fixture named" "from a :go with :go/at"]
   [:plan/since "ms the status last changed" "from the :go event"]
   [:plan/blacklist "targets that failed, skipped when choosing" "from the :go event"]
   [:plan/trunk-failures "failed gather intents per trunk column [x z]; a column that failed twice is skipped when choosing a log" "from the :go event"]
   [:plan/attempts "intent failures in a row" "from the :go event"]
   [:plan/intents "intents started so far; the next one's :intent/id" "after the first intent"]
   [:plan/intent "the intent being executed" "while one runs"]
   [:plan/last "the last intent that ended, with its outcome" "after one ends"]
   [:plan/reason "why the plan failed" "after it failed"]
   [:plan/waiting "why the planner is waiting" "after the first wait"]
   [:plan/waiting-since "ms the current wait began" "while waiting"]
   [:plan/wait "a planner answer meaning: nothing to do yet, for this reason" "returned by next-intent, never stored"]
   [:intent/kind "executor: :walk :dig :collect :craft :place :open-container" "every intent"]
   [:intent/status ":active, :done or :failed" "every intent"]
   [:intent/id "the intent's number in this run, linking its facts in memory" "every started intent"]
   [:intent/goal "the target goal id the intent serves; another target chosen preempts it" "intents the planner starts"]
   [:intent/reason "why it failed, or why the planner abandoned it" "a failed or abandoned intent"]
   [:intent/target "block position it acts on or walks to" "most intents"]
   [:intent/for "what the intent serves (:log), so chains continue only their own" "gather-chain intents"]
   [:intent/trunk "bottom log of the trunk a gather chain works; a failure blacklists it whole" "gather-chain intents"]
   [:intent/stage "executor stage, e.g. :settle :digging :click :verify :take" "staged intents"]
   [:intent/since "ms the stage began" "staged intents"]
   [:intent/started "ms the intent began" "walk and dig"]
   [:intent/still "ticks the bot has been still" "settling intents"]
   [:intent/face "block face it acts on" "dig"]
   [:intent/next-swing "ms of the next arm swing" "dig"]
   [:intent/finish-at "ms after which FINISH may be sent" "dig"]
   [:intent/best-dist "closest it has come to the target" "walk and collect"]
   [:intent/best-tick "tick of the last progress" "walk and collect"]
   [:intent/detour-until "tick a detour ends" "walk, while detouring"]
   [:intent/detour-yaw "heading offset of the detour" "walk, while detouring"]
   [:intent/detours "detours taken" "walk"]
   [:intent/logs-before "logs held when collecting began" "collect"]
   [:intent/blocked-by "leaf block over the drop" "collect, when the drop is covered"]
   [:intent/clears "leaf blocks cleared for this drop" "a collect resumed after clearing"]
   [:intent/resume "the intent to run after clearing a blocker" "a dig that clears a blocker"]
   [:intent/recipe "recipe id to craft" "craft"]
   [:intent/window ":inventory or :table" "craft"]
   [:intent/clicks "clicks still to send" "craft, :click stage"]
   [:intent/result "result item id" "craft"]
   [:intent/makes "items one craft yields" "craft"]
   [:intent/before "result items held before crafting" "craft"]
   [:intent/awaiting "state id a click waits on" "after a click"]
   [:intent/awaiting-window "window id that click went to" "after a click"]
   [:intent/sent-at "ms a click or placement was sent" "after sending"]
   [:intent/item "item to place" "place"]
   [:intent/against "block the placement is against" "place"]
   [:intent/sequence "sequence number of the placement" "place, after sending"]
   ;; ---- events: everything the reducer is given
   [:event/kind ":start :packet :tick :go :closed" "every event"]
   [:event/now "wall-clock ms of a tick" "tick"]
   [:event/rand "a random double in [0, 1] for this tick" "tick"]
   [:event/packet "the decoded packet" "packet"]
   [:event/reason "why the socket closed" "closed"]
   [:start/host "server host" "start"]
   [:start/port "server port" "start"]
   [:start/name "player name" "start"]
   [:go/goals "target goal ids to pursue" "go"]
   [:go/at "where the fixture landed the bot" "go, from a fixture"]
   ;; ---- effects: everything the reducer asks for
   [:effect/kind ":send or :log" "every effect"]
   [:effect/packet "packet to send" "send"]
   [:effect/message "line to log" "log"]
   ;; ---- packets
   [:packet/name "which packet; its other fields are the wire's names, unqualified" "every packet"]
   [:chunk/column "the decoded column, added on the reader thread; never recorded" "level-chunk packets"]])

(def by-attribute
  "attribute → {:doc meaning :when lifetime}."
  (into {} (for [[a doc w] attributes] [a {:doc doc :when w}])))
