(ns clojurecraft.datagen
  "Turn the vanilla server's --reports output into the small EDN tables the bot ships with.
   Run via scripts/datagen.sh (or `clojure -M:datagen <reports-dir> <resources-dir>`)."
  (:require [clojure.data.json :as json]
            [clojure.java.io :as io]
            [clojure.string :as str]))

(defn- strip-ns [s] (str/replace s #"^minecraft:" ""))
(defn- kebab-kw [s] (keyword (str/replace (strip-ns s) "_" "-")))
(defn- name-kw [s] (keyword (strip-ns s)))

(defn packets
  "{state {:s2c {name id} :c2s {name id}}} from reports/packets.json."
  [reports]
  (let [j (json/read-str (slurp (io/file reports "packets.json")))
        dir {"clientbound" :s2c "serverbound" :c2s}]
    (into (sorted-map)
          (for [[state dirs] j]
            [(keyword state)
             (into (sorted-map)
                   (for [[d ps] dirs]
                     [(dir d) (into (sorted-map)
                                    (for [[n m] ps] [(kebab-kw n) (get m "protocol_id")]))]))]))))

(defn blocks
  "[[name type min-state max-state] ...] sorted by state id, from reports/blocks.json."
  [reports]
  (let [j (json/read-str (slurp (io/file reports "blocks.json")))]
    (->> j
         (map (fn [[n m]]
                (let [ids (map #(get % "id") (get m "states"))]
                  [(name-kw n) (name-kw (get-in m ["definition" "type"])) (apply min ids) (apply max ids)])))
         (sort-by #(nth % 2))
         vec)))

(defn registry [reports reg]
  (let [j (json/read-str (slurp (io/file reports "registries.json")))]
    (into (sorted-map)
          (for [[n m] (get-in j [reg "entries"])] [(name-kw n) (get m "protocol_id")]))))

(defn- write-rows [f header rows]
  (with-open [w (io/writer f)]
    (.write w header)
    (.write w "[\n")
    (doseq [r rows] (.write w (str " " (pr-str r) "\n")))
    (.write w "]\n")))

(defn- write-map [f header m]
  (with-open [w (io/writer f)]
    (.write w header)
    (.write w "{\n")
    (doseq [[k v] m] (.write w (str " " (pr-str k) " " (pr-str v) "\n")))
    (.write w "}\n")))

(defn -main [reports out]
  (let [hdr ";; generated by scripts/datagen.sh from vanilla 26.1.2 --reports; do not edit\n"]
    (write-rows (io/file out "blocks.edn") hdr (blocks reports))
    (write-map (io/file out "packets.edn") hdr (packets reports))
    (write-map (io/file out "items.edn") hdr (registry reports "minecraft:item"))
    (write-map (io/file out "entity-types.edn") hdr (registry reports "minecraft:entity_type"))
    (println "wrote" (str out "/{blocks,packets,items,entity-types}.edn"))))
